:sparkles: :rotating_light: expect の引数と戻り値の型パラメーターTを連携
しかし、ビルドするとエラーに。

$ npm run build

> playwright-pom-materials@0.3.0 build
> run-s compile lint

> playwright-pom-materials@0.3.0 compile
> tsc

src/assertions/expect.ts:41:14 - error TS4023: Exported variable 'expect' has or is using name 'APIResponseAssertions' from external module "/Users/takeshi/groovenauts/playwright-pom-materials/node_modules/playwright/types/test" but cannot be named.

41 export const expect = expectBody;
                ~~~~~~

src/assertions/expect.ts:41:14 - error TS4023: Exported variable 'expect' has or is using name 'GenericAssertions' from external module "/Users/takeshi/groovenauts/playwright-pom-materials/node_modules/playwright/types/test" but cannot be named.

41 export const expect = expectBody;
                ~~~~~~

src/assertions/expect.ts:41:14 - error TS4023: Exported variable 'expect' has or is using name 'LocatorAssertions' from external module "/Users/takeshi/groovenauts/playwright-pom-materials/node_modules/playwright/types/test" but cannot be named.

41 export const expect = expectBody;
                ~~~~~~

src/assertions/expect.ts:41:14 - error TS4023: Exported variable 'expect' has or is using name 'PageAssertions' from external module "/Users/takeshi/groovenauts/playwright-pom-materials/node_modules/playwright/types/test" but cannot be named.

41 export const expect = expectBody;
                ~~~~~~

src/assertions/expect.ts:41:14 - error TS4023: Exported variable 'expect' has or is using name 'SnapshotAssertions' from external module "/Users/takeshi/groovenauts/playwright-pom-materials/node_modules/playwright/types/test" but cannot be named.

41 export const expect = expectBody;
                ~~~~~~

src/assertions/expect.ts:41:14 - error TS7056: The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.

41 export const expect = expectBody;
                ~~~~~~

Found 6 errors in the same file, starting at: src/assertions/expect.ts:41

ERROR: "compile" exited with 1.